# Generated by Django 5.1.1 on 2024-09-25 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=51)),
                ("apellido", models.CharField(max_length=51)),
                ("edad", models.IntegerField()),
                ("usuario_id", models.CharField(max_length=18)),
                ("password", models.CharField(max_length=128)),
                ("email", models.EmailField(max_length=200)),
                ("profesion_trabajo", models.CharField(max_length=51, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Proyectos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proyecto_id", models.CharField(max_length=18)),
                ("breve_descripcion", models.CharField(max_length=1250)),
                ("test", models.CharField(max_length=1250, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app_belab.usuario",
                    ),
                ),
            ],
        ),
    ]
