# Generated by Django 5.1.1 on 2024-09-25 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_belab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Consulta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usuario_id", models.CharField(max_length=18)),
                ("consulta", models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name="usuario",
            old_name="usuario_id",
            new_name="NickName",
        ),
        migrations.RemoveField(
            model_name="proyectos",
            name="test",
        ),
        migrations.AlterField(
            model_name="usuario",
            name="password",
            field=models.CharField(max_length=18),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="profesion_trabajo",
            field=models.CharField(default="Ninguna", max_length=51),
        ),
    ]
