# Generated by Django 5.1.1 on 2024-09-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_belab", "0002_consulta_rename_usuario_id_usuario_nickname_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="consulta",
            old_name="usuario_id",
            new_name="NickName",
        ),
        migrations.RenameField(
            model_name="proyectos",
            old_name="proyecto_id",
            new_name="NickName",
        ),
        migrations.RemoveField(
            model_name="proyectos",
            name="usuario",
        ),
        migrations.AddField(
            model_name="consulta",
            name="titulo_consulta",
            field=models.CharField(default="Ninguna", max_length=500),
        ),
        migrations.AddField(
            model_name="proyectos",
            name="nombre_proyecto",
            field=models.CharField(default="Ninguna", max_length=500),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="consulta",
            field=models.CharField(default="Ninguna", max_length=2000),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="breve_descripcion",
            field=models.CharField(default="Ninguna", max_length=1250),
        ),
    ]
