# Generated by Django 5.1.1 on 2024-09-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_belab", "0003_rename_usuario_id_consulta_nickname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consulta",
            name="consulta",
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="consulta",
            name="titulo_consulta",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="breve_descripcion",
            field=models.CharField(max_length=1250),
        ),
        migrations.AlterField(
            model_name="proyectos",
            name="nombre_proyecto",
            field=models.CharField(max_length=500),
        ),
    ]
